### ISSUE TITLE
Избавится от зависимости Спарк и поправить код

### ISSUE THREAD

**Issue by Kasiwadzaki** [Korobko-v/lines#1]
Привет!
Меня зовут Вадим, я разработчик компании BaltInfoCom.  Я провел ревью твоего кода и есть пара моментов которые я бы хотел чтобы ты поправил.  
 - Первое это нужно избавится от лишних зависимостей, так как задание предполагает только написание качественного алгоритма, любую работу с файлами можно выполнять с помощью стандартных java библиотек.  Так что лучше избавиться от лишних зависимостей в pom.xml, по хорошему у тебя в нем должен быть только плагин для создания jar файла и зависимость junit для тестов
 - Так же при запуске jar с любым из тестовых файлов я всегда получаю файл с результатом `Количество групп: 0`.  
 - И необходимо добавить тестирование, пара unit тестов для логики и один интеграционный тест с тестовым маленьким файлом

**Comment by Korobko-v** [comment]
@Kasiwadzaki Вадим, добрый вечер!
От лишних зависимостей избавился, тесты добавил (в т.ч. с проверкой на вывод количества групп в файл). С файлом lng.txt вывод - 1910 групп. Время выполнения программы - 12 секунд (также добавил вывод времени начала и конца выполнения программы в консоль).

**Comment by Kasiwadzaki** [comment]
@Korobko-v Код в порядке, но есть момент. В своей реализации ты сделал упор на то что приходящие строки через запятую это номера телефонов(В тестовом этого указано не было). Поэтому один из наших тестовых файлов lng-big.csv не дает никакого вывода в файл, так как в строках есть точки, то все строки фильтруются твоим регекспом. Файл лежит по ссылке что я скидывал выше, ты можешь запустить его сам и проверить

**Comment by Korobko-v** [comment]
@Kasiwadzaki , я слишком зациклился на примерах в задаче: там одни цифры:) Поменял номера телефонов на слова, а в регулярном выражении теперь вместо цифр проходят все непробельные символы. 
А где файл можно посмотреть? Здесь не вижу, а в задании только lng.txt

**Comment by Kasiwadzaki** [comment]
@Korobko-v https://github.com/PeacockTeam/new-job/releases/tag/v1.0, забыл ссылку скинуть, здесь лежат все тестовые файлы к этому заданию. В случае файла lng-big.csv, у меня все строки оказались в одной группе, а это неверная работа алгоритма

**Comment by Korobko-v** [comment]
@Kasiwadzaki ок, вечером доработаю этот момент. Также хотелось бы более уточнить по поводу регулярки: в задании указаны 2 примера "нежелательных" строк. Правильно ли я понял, что в конечном счёте слова могут быть в кавычках, могут быть без них и могут включать любые символы (кроме лишних кавычек, как в примерах)? Или нам всё-таки нужны исключительно числовые данные, но с возможностью добавлять точку (и запятую?) для дробных значений?

**Comment by Kasiwadzaki** [comment]
@Korobko-v во всех тестовых файлах мы используем натуральные числа и дробные числа. Поэтому с помощью регулярки будет достаточно исключать некорректные строки которые указаны в тестовом, пустые строки с "" и  без.

**Comment by Kasiwadzaki** [comment]
@Korobko-v Как поправишь напиши ответ который получился при выполении большого файла

**Comment by Kasiwadzaki** [comment]
@Korobko-v сыслка на большой файл https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

**Comment by Korobko-v** [comment]
@Kasiwadzaki регулярку поправил. Ответ: 105035

**Comment by Kasiwadzaki** [comment]
@Korobko-v ответ не совсем верный
Попробуй перепроверить

**Comment by Korobko-v** [comment]
@Kasiwadzaki ок

**Comment by Korobko-v** [comment]
@Kasiwadzaki ошибку вижу, но, похоже, ещё нужно будет тесты перепроверить. 5035 правильный ответ?

**Comment by Korobko-v** [comment]
@Kasiwadzaki всё перепроверил, исправленную регулярку запушил (и использовал её-таки в коде, в отличие от предыдущего варианта)) Ответ прежний: 5035

**Comment by Kasiwadzaki** [comment]
@Korobko-v Нет, ответ неверный, предыдущий был ближе к правде

**Comment by Korobko-v** [comment]
@Kasiwadzaki понял, вечером постараюсь исправить, если время ещё есть

**Comment by Kasiwadzaki** [comment]
@Korobko-v Время есть, я смотрю на твои тесты и юнит тест и интеграционный тестируют только успешный вариант прохождения теста. Хороший способ найти баг в своем коде это написать тест который все ломает, попробуй написать 2-3 теста которые не должны пройти. Поэксперементируй с этим

**Comment by Korobko-v** [comment]
@Kasiwadzaki ок, спасибо

**Comment by Korobko-v** [comment]
@Kasiwadzaki самая большая группа тонко намекает: ответ 105036) Добавил тесты: ранее не предусмотрел случай, где числа в кавычках пересекаются с "пропусками" без кавычек. Также для удобства дополнил вывод результатов в консоль.
